server:
  port: 9200

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AnuragBotre/micro-services/tree/master/cloud-configuration-server/src/main/resources/config.yml
          clone-on-start: true